In [6]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from tabula import read_pdf

#df = pd.read_excel(r'C:\Users\user\Downloads\PythonWorkspace\iPythonNotebook\demo.xlsx', sheet_name='Sheet1')
#df = read_pdf(r'C:\Users\user\Downloads\git\DataScience\PythonWorkspace\Assignment\EdaAssignment\Dataset.pdf')
df = pd.read_csv(r'C:\Users\user\Downloads\git\DataScience\PythonWorkspace\Assignment\EdaAssignment\Datasetcsv.csv')
df

     age  year  nodes  status
0     30    64      1       1
1     30    62      3       1
2     30    65      0       1
3     31    59      2       1
4     31    65      4       1
5     33    58     10       1
6     33    60      0       1
7     34    59      0       2
8     34    66      9       2
9     34    58     30       1
10    34    60      1       1
11    34    61     10       1
12    34    67      7       1
13    34    60      0       1
14    35    64     13       1
15    35    63      0       1
16    36    60      1       1
17    36    69      0       1
18    37    60      0       1
19    37    63      0       1
20    37    58      0       1
21    37    59      6       1
22    37    60     15       1
23    37    63      0       1
24    38    69     21       2
25    38    59      2       1
26    38    60      0       1
27    38    60      0       1
28    38    62      3       1
29    38    64      1       1
..   ...   ...    ...     ...
276   67    66      0       1
277   67    61      0       1
278   67    65      0       1
279   68    67      0       1
280   68    68      0       1
281   69    67      8       2
282   69    60      0       1
283   69    65      0       1
284   69    66      0       1
285   70    58      0       2
286   70    58      4       2
287   70    66     14       1
288   70    67      0       1
289   70    68      0       1
290   70    59      8       1
291   70    63      0       1
292   71    68      2       1
293   72    63      0       2
294   72    58      0       1
295   72    64      0       1
296   72    67      3       1
297   73    62      0       1
298   73    68      0       1
299   74    65      3       2
300   74    63      0       1
301   75    62      1       1
302   76    67      0       1
303   77    65      3       1
304   78    65      1       2
305   83    58      2       2

[306 rows x 4 columns]